# Dependencies
markdown:         kramdown
highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
tagline:          'Elegance in Craftsmanship'
description:      'Home page and blog'
url:              http://www.eclecticlogic.com
baseurl:          /

author:
  name:           'Karthik Abram'
  url:            https://twitter.com/eclecticlogic

paginate:         5
paginate_path: "page:num"

# Custom vars

github:
  repo:           https://github.com/eclecticlogic
