# Dependencies
markdown:         kramdown
highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
tagline:          'Elegance in Craftsmanship'
description:      'We build next-generation interactive and scalable systems. With deep expertise in the Java Platform, mobile, transactional systems, persistence models, analytics and high performance computing, we solve complex problems and turn ideas into reality.'
url:              http://www.eclecticlogic.com
baseurl:          /

author:
  name:           'Karthik Abram'
  url:            https://twitter.com/eclecticlogic

paginate:         5
paginate_path: "blog/page:num"

# Custom vars

github:
  repo:           https://github.com/eclecticlogic
